export const navMap: Record<string, string> = {
'thống kê tổng quan': '/',
'dashboard': '/',
'trang chủ': '/',
'tổng quan': '/',
'thống kê sự cố': '/incident-report-page',
'báo cáo sự cố': '/incident-report-page',
'báo lỗi': '/incident-report-page',
'thống kê góp ý': '/feadback-dashboard',
'feedback dashboard': '/feadback-dashboard',
'tin tức': '/news',
'news': '/news',
'bản tin': '/news',
'lịch': '/calendar',
'calendar': '/calendar',
'lịch làm việc': '/calendar',
'danh sách sự cố': '/all-incidents-page',
'tất cả sự cố': '/all-incidents-page',
'lịch sử sự cố': '/all-incidents-page',
'hàng đợi': '/incident-queue',
'queue': '/incident-queue',
'thông báo sự cố khẩn cấp': '/incident-queue',
'sự cố khẩn cấp': '/incident-queue',
'hòn trắng': '/public-ideas-page',
'hòm trắng': '/public-ideas-page',
'đánh giá công khai': '/public-ideas-page',
'ý tưởng': '/public-ideas-page',
'sáng kiến': '/public-ideas-page',
'hòm hồng': '/admin-inbox-pink',
'đánh giá ẩn danh': '/admin-inbox-pink',
'đánh giá kín': '/admin-inbox-pink',
'góp ý kín': '/admin-inbox-pink',
'lưu trữ': '/kaizen-bank-page',
'kaizen': '/kaizen-bank-page',
'ngân hàng kaizen': '/kaizen-bank-page',
'người dùng': '/users',
'nhân viên': '/users',
'hồ sơ': '/profile',
'profile': '/profile',
'hòm thư góp ý công khai' : '/public-ideas-page',
'hòm thu góp ý ẩn danh' : '/admin-inbox-pink',
};