@echo off
REM =============================================================================
REM SmartFactory CONNECT - Auto Update Local IP (Windows Batch)
REM =============================================================================
REM Script nay tu dong detect IP va cap nhat cau hinh khi doi mang
REM Usage: update-local-ip.bat
REM =============================================================================

setlocal enabledelayedexpansion
chcp 65001 >nul 2>&1

echo.
echo ================================================================
echo    SmartFactory CONNECT - Local IP Configuration
echo ================================================================
echo.

REM Get script directory
set "SCRIPT_DIR=%~dp0"
set "PROJECT_DIR=%SCRIPT_DIR%.."
cd /d "%PROJECT_DIR%"

REM =============================================================================
REM STEP 1: Detect Local IP
REM =============================================================================
echo [1/5] Detecting local IP address...

REM Try to get IP from ipconfig (prefer IPv4)
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /i "IPv4" ^| findstr /v "169.254"') do (
    set "IP_TEMP=%%a"
    REM Remove leading space
    set "LOCAL_IP=!IP_TEMP:~1!"
    goto :found_ip
)

REM Fallback: hostname method
for /f "tokens=*" %%a in ('powershell -command "(Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.InterfaceAlias -notmatch 'Loopback|VMware|VirtualBox' -and $_.IPAddress -notmatch '^127\.' } | Select-Object -First 1).IPAddress"') do (
    set "LOCAL_IP=%%a"
)

:found_ip
if "%LOCAL_IP%"=="" (
    echo [ERROR] Cannot detect IP address!
    echo Please check your network connection.
    pause
    exit /b 1
)

echo    [OK] Found IP: %LOCAL_IP%

REM =============================================================================
REM STEP 2: Update Backend .env
REM =============================================================================
echo.
echo [2/5] Updating Backend configuration...

set "ENV_FILE=%PROJECT_DIR%\backend\.env"
set "ENV_LOCAL=%PROJECT_DIR%\backend\.env.local"

REM Use .env.local if exists
if exist "%ENV_LOCAL%" (
    set "TARGET_ENV=%ENV_LOCAL%"
) else (
    set "TARGET_ENV=%ENV_FILE%"
)

REM Backup
if exist "%TARGET_ENV%" (
    copy /Y "%TARGET_ENV%" "%TARGET_ENV%.backup" >nul 2>&1
)

REM Create CORS value
set "CORS_VALUE=http://localhost,http://localhost:80,http://localhost:5173,http://%LOCAL_IP%,http://%LOCAL_IP%:80,http://%LOCAL_IP%:5173,http://%LOCAL_IP%:3000"

REM Update using PowerShell for reliability
powershell -command "$content = Get-Content '%TARGET_ENV%' -Raw -ErrorAction SilentlyContinue; if (-not $content) { $content = '' }; $cors = '%CORS_VALUE%'; if ($content -match '(?m)^CORS_ORIGINS=') { $content = $content -replace '(?m)^CORS_ORIGINS=.*', \"CORS_ORIGINS=$cors\" } else { $content += \"`nCORS_ORIGINS=$cors\" }; if ($content -match '(?m)^HOST=') { $content = $content -replace '(?m)^HOST=.*', 'HOST=0.0.0.0' } else { $content += \"`nHOST=0.0.0.0\" }; $content | Set-Content '%TARGET_ENV%' -NoNewline"

echo    [OK] Updated: %TARGET_ENV%

REM =============================================================================
REM STEP 3: Update Frontend .env.local
REM =============================================================================
echo.
echo [3/5] Updating Frontend configuration...

set "FRONTEND_ENV=%PROJECT_DIR%\frontend\.env.local"

REM Get timestamp
for /f %%a in ('powershell -command "Get-Date -Format 'yyyy-MM-dd HH:mm:ss'"') do set "TIMESTAMP=%%a"

(
echo # Auto-generated by update-local-ip.bat
echo # Generated: %TIMESTAMP%
echo # Local IP: %LOCAL_IP%
echo.
echo VITE_API_URL=http://%LOCAL_IP%:3000
echo VITE_RAG_URL=http://%LOCAL_IP%:8001
echo VITE_WS_URL=ws://%LOCAL_IP%:3000
) > "%FRONTEND_ENV%"

echo    [OK] Created: %FRONTEND_ENV%

REM =============================================================================
REM STEP 4: Generate Mobile App Config
REM =============================================================================
echo.
echo [4/5] Generating Mobile App configuration...

set "MOBILE_CONFIG_DIR=%PROJECT_DIR%\..\SmartFactory_CONNECT_App\lib\core\config"
set "MOBILE_CONFIG_FILE=%MOBILE_CONFIG_DIR%\local_network_config.dart"

if exist "%PROJECT_DIR%\..\SmartFactory_CONNECT_App\lib" (
    if not exist "%MOBILE_CONFIG_DIR%" mkdir "%MOBILE_CONFIG_DIR%"
    
    REM Get ISO timestamp
    for /f %%a in ('powershell -command "(Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')"') do set "ISO_TIMESTAMP=%%a"
    
    (
echo // Auto-generated by update-local-ip.bat
echo // Generated: %TIMESTAMP%
echo // Run script again when changing network
echo.
echo /// Local network configuration
echo /// Import this file and use LocalNetworkConfig.apiBaseUrl
echo class LocalNetworkConfig {
echo   /// Current local server IP
echo   static const String serverIP = '%LOCAL_IP%';
echo.
echo   /// API Base URL ^(Backend^)
echo   static const String apiBaseUrl = 'http://%LOCAL_IP%:3000';
echo.
echo   /// RAG Service URL
echo   static const String ragUrl = 'http://%LOCAL_IP%:8001';
echo.
echo   /// WebSocket URL
echo   static const String wsUrl = 'ws://%LOCAL_IP%:3000';
echo.
echo   /// Check if using local network mode
echo   static const bool isLocalNetwork = true;
echo.
echo   /// Last updated timestamp
echo   static const String lastUpdated = '%ISO_TIMESTAMP%';
echo }
    ) > "%MOBILE_CONFIG_FILE%"
    
    echo    [OK] Created: %MOBILE_CONFIG_FILE%
) else (
    echo    [WARN] Mobile app directory not found, skipping...
)

REM =============================================================================
REM STEP 5: Generate Connection Info
REM =============================================================================
echo.
echo [5/5] Generating connection info...

set "INFO_FILE=%PROJECT_DIR%\LOCAL_NETWORK_INFO.txt"

(
echo ================================================================
echo    SmartFactory CONNECT - Local Network Configuration
echo ================================================================
echo.
echo Generated: %TIMESTAMP%
echo Server IP: %LOCAL_IP%
echo.
echo ================================================================
echo CONNECTION URLS
echo ================================================================
echo.
echo WEB DASHBOARD:
echo    URL: http://%LOCAL_IP%
echo.
echo BACKEND API:
echo    Base URL: http://%LOCAL_IP%:3000
echo    Health Check: http://%LOCAL_IP%:3000/health
echo.
echo RAG SERVICE:
echo    URL: http://%LOCAL_IP%:8001
echo.
echo MOBILE APP CONFIGURATION:
echo    API URL: http://%LOCAL_IP%:3000
echo    RAG URL: http://%LOCAL_IP%:8001
echo.
echo ================================================================
echo IMPORTANT NOTES
echo ================================================================
echo.
echo 1. All devices must be on the same WiFi/LAN network
echo 2. Run this script again when changing WiFi network
echo 3. Make sure Windows Firewall allows ports: 80, 3000, 5432, 27017, 8001
echo.
echo ================================================================
echo QUICK COMMANDS
echo ================================================================
echo.
echo Start services:
echo    docker-compose up -d
echo.
echo Restart after IP change:
echo    docker-compose restart backend frontend
echo.
echo Test API:
echo    curl http://%LOCAL_IP%:3000/health
echo.
) > "%INFO_FILE%"

echo    [OK] Created: %INFO_FILE%

REM =============================================================================
REM SUMMARY
REM =============================================================================
echo.
echo ================================================================
echo    Configuration Updated Successfully!
echo ================================================================
echo.
echo Server IP: %LOCAL_IP%
echo.
echo Access URLs:
echo    Web Dashboard:  http://%LOCAL_IP%
echo    Backend API:    http://%LOCAL_IP%:3000
echo    RAG Service:    http://%LOCAL_IP%:8001
echo.
echo Mobile App Config:
echo    API URL: http://%LOCAL_IP%:3000
echo.
echo Next Steps:
echo    1. Restart services: docker-compose restart backend frontend
echo    2. Update Mobile App: Import local_network_config.dart
echo    3. Share IP with team: type LOCAL_NETWORK_INFO.txt
echo.

REM Ask to restart Docker services
set /p "RESTART=Do you want to restart Docker services now? (y/N): "
if /i "%RESTART%"=="y" (
    echo.
    echo Restarting Docker services...
    cd /d "%PROJECT_DIR%"
    
    REM Check if local compose file exists
    if exist "docker-compose.local.yml" (
        echo    Using docker-compose.local.yml
        docker-compose -f docker-compose.local.yml restart backend frontend
    ) else (
        docker-compose restart backend frontend
    )
    echo [OK] Services restarted!
)

echo.
pause
