# =============================================================================
# SmartFactory CONNECT - Auto Update Local IP (Windows PowerShell)
# =============================================================================
# Script nay tu dong detect IP va cap nhat cau hinh khi doi mang
# Usage: .\update-local-ip.ps1
# =============================================================================

$ErrorActionPreference = "Continue"

# Get script directory
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectDir = Split-Path -Parent $ScriptDir

Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "   SmartFactory CONNECT - Local IP Configuration              " -ForegroundColor Cyan
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""

# =============================================================================
# STEP 1: Detect Local IP
# =============================================================================
Write-Host "[1/5] Detecting local IP address..." -ForegroundColor Yellow

# Get active network adapter IP (prefer WiFi or Ethernet, exclude virtual adapters)
$NetworkAdapters = Get-NetIPAddress -AddressFamily IPv4 | Where-Object {
    $_.InterfaceAlias -notmatch "Loopback|VMware|VirtualBox|Hyper-V|vEthernet|Docker" -and
    $_.IPAddress -notmatch "^127\." -and
    $_.IPAddress -notmatch "^169\.254\." -and
    $_.PrefixOrigin -ne "WellKnown"
}

$LocalIP = $NetworkAdapters | Select-Object -First 1 -ExpandProperty IPAddress

if (-not $LocalIP) {
    Write-Host "[ERROR] Cannot detect IP address!" -ForegroundColor Red
    Write-Host "   Please check your network connection."
    Read-Host "Press Enter to exit"
    exit 1
}

Write-Host "   [OK] Detected IP: " -ForegroundColor Green -NoNewline
Write-Host $LocalIP -ForegroundColor Cyan

# Show all detected IPs for reference
Write-Host ""
Write-Host "   All network interfaces:" -ForegroundColor Gray
$NetworkAdapters | ForEach-Object {
    Write-Host "     - $($_.InterfaceAlias): $($_.IPAddress)" -ForegroundColor Gray
}

# =============================================================================
# STEP 2: Update Backend .env
# =============================================================================
Write-Host ""
Write-Host "[2/5] Updating Backend configuration..." -ForegroundColor Yellow

$BackendEnv = Join-Path $ProjectDir "backend\.env"
$BackendEnvLocal = Join-Path $ProjectDir "backend\.env.local"

# Determine which env file to use
if (Test-Path $BackendEnvLocal) {
    $EnvFile = $BackendEnvLocal
} elseif (Test-Path $BackendEnv) {
    $EnvFile = $BackendEnv
} else {
    Write-Host "   [WARN] No backend .env file found, creating..." -ForegroundColor Yellow
    $EnvFile = $BackendEnv
    New-Item -Path $EnvFile -ItemType File -Force | Out-Null
}

# Backup original
Copy-Item $EnvFile "${EnvFile}.backup" -Force -ErrorAction SilentlyContinue

# Read current content
$EnvContent = Get-Content $EnvFile -Raw -ErrorAction SilentlyContinue
if (-not $EnvContent) { $EnvContent = "" }

# CORS value
$CorsValue = "http://localhost,http://localhost:80,http://localhost:5173,http://${LocalIP},http://${LocalIP}:80,http://${LocalIP}:5173,http://${LocalIP}:3000"

# Update CORS_ORIGINS
if ($EnvContent -match "^CORS_ORIGINS=.*" ) {
    $EnvContent = $EnvContent -replace "(?m)^CORS_ORIGINS=.*", "CORS_ORIGINS=$CorsValue"
} else {
    $EnvContent += "`nCORS_ORIGINS=$CorsValue"
}

# Update HOST
if ($EnvContent -match "^HOST=.*") {
    $EnvContent = $EnvContent -replace "(?m)^HOST=.*", "HOST=0.0.0.0"
} else {
    $EnvContent += "`nHOST=0.0.0.0"
}

# Save
$EnvContent | Set-Content $EnvFile -NoNewline
Write-Host "   [OK] Updated: $EnvFile" -ForegroundColor Green

# =============================================================================
# STEP 3: Update Frontend .env.local
# =============================================================================
Write-Host ""
Write-Host "[3/5] Updating Frontend configuration..." -ForegroundColor Yellow

$FrontendEnv = Join-Path $ProjectDir "frontend\.env.local"
$Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$FrontendContent = @"
# Auto-generated by update-local-ip.ps1
# Generated: $Timestamp
# Local IP: $LocalIP

VITE_API_URL=http://${LocalIP}:3000
VITE_RAG_URL=http://${LocalIP}:8001
VITE_WS_URL=ws://${LocalIP}:3000
"@

$FrontendContent | Set-Content $FrontendEnv
Write-Host "   [OK] Created: $FrontendEnv" -ForegroundColor Green

# =============================================================================
# STEP 4: Generate Mobile App Config
# =============================================================================
Write-Host ""
Write-Host "[4/5] Generating Mobile App configuration..." -ForegroundColor Yellow

$MobileConfigDir = Join-Path (Split-Path -Parent $ProjectDir) "SmartFactory_CONNECT_App\lib\core\config"
$MobileConfigFile = Join-Path $MobileConfigDir "local_network_config.dart"

if (Test-Path (Split-Path -Parent $MobileConfigDir)) {
    # Create directory if needed
    New-Item -Path $MobileConfigDir -ItemType Directory -Force -ErrorAction SilentlyContinue | Out-Null
    
    $IsoTimestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    
    $DartContent = @"
// Auto-generated by update-local-ip.ps1
// Generated: $Timestamp
// Run script again when changing network

/// Local network configuration
/// Import this file and use LocalNetworkConfig.apiBaseUrl
class LocalNetworkConfig {
  /// Current local server IP
  static const String serverIP = '$LocalIP';
  
  /// API Base URL (Backend)
  static const String apiBaseUrl = 'http://${LocalIP}:3000';
  
  /// RAG Service URL
  static const String ragUrl = 'http://${LocalIP}:8001';
  
  /// WebSocket URL
  static const String wsUrl = 'ws://${LocalIP}:3000';
  
  /// Check if using local network mode
  static const bool isLocalNetwork = true;
  
  /// Last updated timestamp
  static const String lastUpdated = '$IsoTimestamp';
}
"@
    
    $DartContent | Set-Content $MobileConfigFile
    Write-Host "   [OK] Created: $MobileConfigFile" -ForegroundColor Green
} else {
    Write-Host "   [WARN] Mobile app directory not found, skipping..." -ForegroundColor Yellow
}

# =============================================================================
# STEP 5: Generate Connection Info
# =============================================================================
Write-Host ""
Write-Host "[5/5] Generating connection info..." -ForegroundColor Yellow

$InfoFile = Join-Path $ProjectDir "LOCAL_NETWORK_INFO.txt"

$InfoContent = @"
================================================================
   SmartFactory CONNECT - Local Network Configuration
================================================================

Generated: $Timestamp
Server IP: $LocalIP

================================================================
CONNECTION URLS
================================================================

WEB DASHBOARD:
   URL: http://$LocalIP
   (Truy cap tu bat ky thiet bi nao trong cung mang)

BACKEND API:
   Base URL: http://${LocalIP}:3000
   Health Check: http://${LocalIP}:3000/health
   API Endpoint: http://${LocalIP}:3000/api

RAG SERVICE:
   URL: http://${LocalIP}:8001
   Health Check: http://${LocalIP}:8001/health

MOBILE APP CONFIGURATION:
   API URL: http://${LocalIP}:3000
   RAG URL: http://${LocalIP}:8001

================================================================
IMPORTANT NOTES
================================================================

1. Tat ca thiet bi phai ket noi cung mang WiFi/LAN
2. Neu doi mang WiFi, chay lai script: .\scripts\update-local-ip.ps1
3. Dam bao Windows Firewall cho phep ports: 80, 3000, 5432, 27017, 8001

================================================================
QUICK COMMANDS
================================================================

# Khoi dong services:
docker-compose up -d

# Xem logs:
docker-compose logs -f

# Restart sau khi doi IP:
docker-compose restart backend frontend

# Test API:
Invoke-WebRequest http://${LocalIP}:3000/health

================================================================
FIREWALL SETUP (Run as Administrator if needed)
================================================================

# Allow Backend API (port 3000):
netsh advfirewall firewall add rule name="SmartFactory Backend" dir=in action=allow protocol=TCP localport=3000

# Allow Web (port 80):
netsh advfirewall firewall add rule name="SmartFactory Web" dir=in action=allow protocol=TCP localport=80

# Allow RAG Service (port 8001):
netsh advfirewall firewall add rule name="SmartFactory RAG" dir=in action=allow protocol=TCP localport=8001

"@

$InfoContent | Set-Content $InfoFile
Write-Host "   [OK] Created: $InfoFile" -ForegroundColor Green

# =============================================================================
# SUMMARY
# =============================================================================
Write-Host ""
Write-Host "================================================================" -ForegroundColor Green
Write-Host "   Configuration Updated Successfully!                         " -ForegroundColor Green
Write-Host "================================================================" -ForegroundColor Green
Write-Host ""
Write-Host "Server IP: " -ForegroundColor Cyan -NoNewline
Write-Host $LocalIP -ForegroundColor Yellow
Write-Host ""
Write-Host "Access URLs:" -ForegroundColor Cyan
Write-Host "   Web Dashboard:  " -NoNewline
Write-Host "http://$LocalIP" -ForegroundColor Yellow
Write-Host "   Backend API:    " -NoNewline
Write-Host "http://${LocalIP}:3000" -ForegroundColor Yellow
Write-Host "   RAG Service:    " -NoNewline
Write-Host "http://${LocalIP}:8001" -ForegroundColor Yellow
Write-Host ""
Write-Host "Mobile App Config:" -ForegroundColor Cyan
Write-Host "   API URL: " -NoNewline
Write-Host "http://${LocalIP}:3000" -ForegroundColor Yellow
Write-Host ""
Write-Host "Next Steps:" -ForegroundColor Yellow
Write-Host "   1. Restart services: " -NoNewline
Write-Host "docker-compose restart backend frontend" -ForegroundColor Cyan
Write-Host "   2. Update Mobile App: Import " -NoNewline
Write-Host "local_network_config.dart" -ForegroundColor Cyan
Write-Host "   3. Share IP with team: " -NoNewline
Write-Host "Get-Content LOCAL_NETWORK_INFO.txt" -ForegroundColor Cyan
Write-Host ""

# Optional: Ask to restart Docker services
$restart = Read-Host "Do you want to restart Docker services now? (y/N)"
if ($restart -eq 'y' -or $restart -eq 'Y') {
    Write-Host ""
    Write-Host "Restarting Docker services..." -ForegroundColor Yellow
    Set-Location $ProjectDir
    
    # Check if local compose file exists
    if (Test-Path "docker-compose.local.yml") {
        Write-Host "   Using docker-compose.local.yml" -ForegroundColor Cyan
        docker-compose -f docker-compose.local.yml restart backend frontend
    } else {
        docker-compose restart backend frontend
    }
    Write-Host "[OK] Services restarted!" -ForegroundColor Green
}

Write-Host ""
Read-Host "Press Enter to exit"
