#!/bin/bash
# =============================================================================
# SmartFactory CONNECT - Auto Update Local IP (macOS/Linux)
# =============================================================================
# Script nay tu dong detect IP va cap nhat cau hinh khi doi mang
# Usage: ./update-local-ip.sh
# =============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo ""
echo -e "${BLUE}================================================================${NC}"
echo -e "${BLUE}   SmartFactory CONNECT - Local IP Configuration              ${NC}"
echo -e "${BLUE}================================================================${NC}"
echo ""

# =============================================================================
# STEP 1: Detect Local IP
# =============================================================================
echo -e "${YELLOW}[1/5] Detecting local IP address...${NC}"

# Try different methods to get IP
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    LOCAL_IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "")
    if [ -z "$LOCAL_IP" ]; then
        LOCAL_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | head -1 | awk '{print $2}')
    fi
else
    # Linux
    LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || ip route get 1 | awk '{print $7}' | head -1)
fi

if [ -z "$LOCAL_IP" ]; then
    echo -e "${RED}[ERROR] Cannot detect IP address!${NC}"
    echo "   Please check your network connection."
    exit 1
fi

echo -e "   ${GREEN}[OK] Detected IP: ${CYAN}$LOCAL_IP${NC}"

# =============================================================================
# STEP 2: Update Backend .env
# =============================================================================
echo ""
echo -e "${YELLOW}[2/5] Updating Backend configuration...${NC}"

BACKEND_ENV="$PROJECT_DIR/backend/.env"
BACKEND_ENV_LOCAL="$PROJECT_DIR/backend/.env.local"

# Use .env.local if exists, otherwise .env
if [ -f "$BACKEND_ENV_LOCAL" ]; then
    ENV_FILE="$BACKEND_ENV_LOCAL"
elif [ -f "$BACKEND_ENV" ]; then
    ENV_FILE="$BACKEND_ENV"
else
    echo -e "   ${YELLOW}[WARN] No backend .env file found, creating...${NC}"
    ENV_FILE="$BACKEND_ENV"
    touch "$ENV_FILE"
fi

# Backup original
cp "$ENV_FILE" "${ENV_FILE}.backup" 2>/dev/null || true

# Update or add CORS_ORIGINS
CORS_VALUE="http://localhost,http://localhost:80,http://localhost:5173,http://${LOCAL_IP},http://${LOCAL_IP}:80,http://${LOCAL_IP}:5173,http://${LOCAL_IP}:3000"

if grep -q "^CORS_ORIGINS=" "$ENV_FILE"; then
    # Update existing
    if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' "s|^CORS_ORIGINS=.*|CORS_ORIGINS=${CORS_VALUE}|" "$ENV_FILE"
    else
        sed -i "s|^CORS_ORIGINS=.*|CORS_ORIGINS=${CORS_VALUE}|" "$ENV_FILE"
    fi
else
    # Add new
    echo "CORS_ORIGINS=${CORS_VALUE}" >> "$ENV_FILE"
fi

# Ensure HOST=0.0.0.0 for binding
if grep -q "^HOST=" "$ENV_FILE"; then
    if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' "s|^HOST=.*|HOST=0.0.0.0|" "$ENV_FILE"
    else
        sed -i "s|^HOST=.*|HOST=0.0.0.0|" "$ENV_FILE"
    fi
else
    echo "HOST=0.0.0.0" >> "$ENV_FILE"
fi

echo -e "   ${GREEN}[OK] Updated: $ENV_FILE${NC}"

# =============================================================================
# STEP 3: Update Frontend .env.local
# =============================================================================
echo ""
echo -e "${YELLOW}[3/5] Updating Frontend configuration...${NC}"

FRONTEND_ENV="$PROJECT_DIR/frontend/.env.local"

cat > "$FRONTEND_ENV" << EOF
# Auto-generated by update-local-ip.sh
# Generated: $(date)
# Local IP: $LOCAL_IP

VITE_API_URL=http://${LOCAL_IP}:3000
VITE_RAG_URL=http://${LOCAL_IP}:8001
VITE_WS_URL=ws://${LOCAL_IP}:3000
EOF

echo -e "   ${GREEN}[OK] Created: $FRONTEND_ENV${NC}"

# =============================================================================
# STEP 4: Generate Mobile App Config
# =============================================================================
echo ""
echo -e "${YELLOW}[4/5] Generating Mobile App configuration...${NC}"

MOBILE_CONFIG_DIR="$PROJECT_DIR/../SmartFactory_CONNECT_App/lib/core/config"
MOBILE_CONFIG_FILE="$MOBILE_CONFIG_DIR/local_network_config.dart"

# Create directory if not exists
mkdir -p "$MOBILE_CONFIG_DIR" 2>/dev/null || true

if [ -d "$MOBILE_CONFIG_DIR" ]; then
    cat > "$MOBILE_CONFIG_FILE" << EOF
// Auto-generated by update-local-ip.sh
// Generated: $(date)
// Run script again when changing network

/// Local network configuration
/// Import this file and use LocalNetworkConfig.apiBaseUrl
class LocalNetworkConfig {
  /// Current local server IP
  static const String serverIP = '$LOCAL_IP';
  
  /// API Base URL (Backend)
  static const String apiBaseUrl = 'http://$LOCAL_IP:3000';
  
  /// RAG Service URL
  static const String ragUrl = 'http://$LOCAL_IP:8001';
  
  /// WebSocket URL
  static const String wsUrl = 'ws://$LOCAL_IP:3000';
  
  /// Check if using local network mode
  static const bool isLocalNetwork = true;
  
  /// Last updated timestamp
  static const String lastUpdated = '$(date -u +"%Y-%m-%dT%H:%M:%SZ")';
}
EOF
    echo -e "   ${GREEN}[OK] Created: $MOBILE_CONFIG_FILE${NC}"
else
    echo -e "   ${YELLOW}[WARN] Mobile app directory not found, skipping...${NC}"
fi

# =============================================================================
# STEP 5: Generate Connection Info
# =============================================================================
echo ""
echo -e "${YELLOW}[5/5] Generating connection info...${NC}"

INFO_FILE="$PROJECT_DIR/LOCAL_NETWORK_INFO.txt"

cat > "$INFO_FILE" << EOF
================================================================
   SmartFactory CONNECT - Local Network Configuration
================================================================

Generated: $(date)
Server IP: $LOCAL_IP

================================================================
CONNECTION URLS
================================================================

WEB DASHBOARD:
   URL: http://$LOCAL_IP
   (Truy cap tu bat ky thiet bi nao trong cung mang)

BACKEND API:
   Base URL: http://$LOCAL_IP:3000
   Health Check: http://$LOCAL_IP:3000/health
   API Endpoint: http://$LOCAL_IP:3000/api

RAG SERVICE:
   URL: http://$LOCAL_IP:8001
   Health Check: http://$LOCAL_IP:8001/health

MOBILE APP CONFIGURATION:
   API URL: http://$LOCAL_IP:3000
   RAG URL: http://$LOCAL_IP:8001

================================================================
IMPORTANT NOTES
================================================================

1. Tat ca thiet bi phai ket noi cung mang WiFi/LAN
2. Neu doi mang WiFi, chay lai script: ./scripts/update-local-ip.sh
3. Dam bao Firewall cho phep ports: 80, 3000, 5432, 27017, 8001

================================================================
QUICK COMMANDS
================================================================

# Khoi dong services:
docker-compose up -d

# Xem logs:
docker-compose logs -f

# Restart sau khi doi IP:
docker-compose restart backend frontend

# Test API:
curl http://$LOCAL_IP:3000/health

EOF

echo -e "   ${GREEN}[OK] Created: $INFO_FILE${NC}"

# =============================================================================
# SUMMARY
# =============================================================================
echo ""
echo -e "${GREEN}================================================================${NC}"
echo -e "${GREEN}   Configuration Updated Successfully!                         ${NC}"
echo -e "${GREEN}================================================================${NC}"
echo ""
echo -e "${CYAN}Server IP: ${YELLOW}$LOCAL_IP${NC}"
echo ""
echo -e "${CYAN}Access URLs:${NC}"
echo -e "   Web Dashboard:  ${YELLOW}http://$LOCAL_IP${NC}"
echo -e "   Backend API:    ${YELLOW}http://$LOCAL_IP:3000${NC}"
echo -e "   RAG Service:    ${YELLOW}http://$LOCAL_IP:8001${NC}"
echo ""
echo -e "${CYAN}Mobile App Config:${NC}"
echo -e "   API URL: ${YELLOW}http://$LOCAL_IP:3000${NC}"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo -e "   1. Restart services: ${CYAN}docker-compose -f docker-compose.local.yml restart backend frontend${NC}"
echo -e "   2. Update Mobile App: Import ${CYAN}local_network_config.dart${NC}"
echo -e "   3. Share IP with team: ${CYAN}cat LOCAL_NETWORK_INFO.txt${NC}"
echo ""

# Optional: Ask to restart Docker services
read -p "Do you want to restart Docker services now? (y/N): " RESTART
if [[ "$RESTART" =~ ^[Yy]$ ]]; then
    echo ""
    echo -e "${YELLOW}Restarting Docker services...${NC}"
    cd "$PROJECT_DIR"
    
    # Check if local compose file exists
    if [ -f "docker-compose.local.yml" ]; then
        echo -e "${CYAN}   Using docker-compose.local.yml${NC}"
        docker-compose -f docker-compose.local.yml restart backend frontend
    else
        docker-compose restart backend frontend
    fi
    echo -e "${GREEN}[OK] Services restarted!${NC}"
fi

echo ""
echo -e "${GREEN}Done!${NC}"
